version: 1.0

functions:
  dummy-hello-world:
    lang: nodejs
    service: services/dummy
    action: Dummy.HelloWorld
    alias:
      method: POST
      path: dummy/hello-world
    environement:
      NODE_ENV: development
  dummy-not-hello-world:
    lang: nodejs
    service: services/dummy
    action: Dummy.NotHelloWorld
    alias:
      method: GET
      path: dummy/not-hello-world
    environement:
      NODE_ENV: development
