apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: "{{ .Values.app.name }}-ing"
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Values.app.name }}-svc"
          servicePort: 3000
        path: /
